### PR TITLE
Fix test to always use invariant culture

### PR DESCRIPTION
**Pull request by HaoK**
cc @divega

### CODE REVIEW

**Comment by divega** [comment]
@HaoK could you briefly explain how this is going to help? I get that we are now producing theory data using invariant culture, I just want to understand how we are consuming this in the tests and how the culture has an impact.

**Comment by HaoK** [comment]
There was a test bug where this test fails when running with current culture is not en-us. This fixes that as the underlying code in config binder only converts from invariant culture anyways.

**Comment by divega** [comment]
:shipit:

> This fixes that as the underlying code in config binder only converts from invariant culture anyways.

I will file a bug on that :smile:

**Comment by MichaCo** [comment]
There is also the Microsoft.AspNet.Testing.ReplaceCultureAttribute which temporarily sets the current thread culture.

Regarding the binder using invariant only; we discussed that in #98. 
I think it is dangerous to assume that the development and maybe production/other environments run with the same system culture. 
And in those cases with current culture you might get different results reading the same configuration 

But extending the binder to take the culture optionally, sounds like a good idea!

**Comment by HaoK** [comment]
758e11ecee0c30e12d3498182a799148d7d45a8c

**Pull request closed without merging**
