### PR TITLE
Allow null name to mean default instance

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/aspnet/Options/issues/220

@ajcvickers @Tratcher

### CODE REVIEW

**Comment by HaoK** [comment]
The only danger with this change, is here:

`services.Configure(name: null, o => o.DoWhatever())` means configure all instances regardless of name
`IOptionsMonitor.Get(name: null)` means give me the Options.DefaultInstance

I don't think this is too big of a deal, but its worth noting that where's just trading a different set of inconsistencies.

**Comment by HaoK** [comment]
I'm not opposed to keeping things as they are, where null is allowed in only a few places, and in general it throws.  I don't think this defaulting behavior will be generally useful.

**Comment by Tratcher** [comment]
It's the inconsistency that bothers me. This PR at least addresses that.

**Comment by HaoK** [comment]
I guess that's fair, we won't throw for null names anywhere

**Pull request merged**
