### PR TITLE
Support for enum types

### PR DESCRIPTION
**Pull request by dtkujawski**
Current options binding does not support enums. 

(note: for the unit tests, I picked a random enum from the System namespace.  I'm not actually suggesting that people might want to use UriKind in their configuration files.  Although, I guess you never know!)

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@dtkujawski__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by Eilon** [comment]
@dtkujawski can you rebase and test on the latest code? We recently changed this file and I want to ensure your changes still work.

**Comment by dtkujawski** [comment]
Eilon - had to make a minor modification for it to work with latest.  Should be good to go now.

**Comment by dtkujawski** [comment]
Can I ask a noob-question?  Is there a resource you could point me to which explains a good way to link my custom project/solution to use versions of these assemblies that I build locally?  Currently I am just using the unit tests to verify the code, but I'd like to make use of these changes in my custom solution until they get merged into the next CTP.

**Comment by dtkujawski** [comment]
PS: Looks like the CI failed, but it appears due to a configuration issue with CI possibly (permission failure)

**Comment by Eilon** [comment]
The Travis CI failed due to the shell script not having execute permissions. @davidfowl fixing.

**Comment by Eilon** [comment]
The change looks good - nice test too. @HaoK do you want to take a quick look?

BTW I don't like that exceptions are ignored here, so I filed #55 .

**Comment by HaoK** [comment]
Nice! :shipit:

**Comment by davidfowl** [comment]
@dtkujawski did you change the persmissions on the build.sh file? Looks like you did.

**Comment by dtkujawski** [comment]
@davidfowl  ahh weird - didn't realize that happened.  I've pushed a commit that has the execute permission re-instated.  Just waiting for the Appveyor process to grab it.

**Comment by Eilon** [comment]
@dtkujawski merged, thanks!

**Pull request merged**
