### PR TITLE
Remove conditional compilation for options

### PR DESCRIPTION
**Pull request by HaoK**
Had to tweak the reflection code to run on all targets

Fixes https://github.com/aspnet/Options/issues/35

cc @divega

### CODE REVIEW

**Comment by davidfowl** [comment]
:shipit:

**Comment by davidfowl** [comment]
@HaoK what happened to this?

**Comment by HaoK** [comment]
I forgot about it, I'll resurrect and get this in

**Comment by HaoK** [comment]
@davidfowl Eww, so I had to manually write code to crawl to build up all the properties because core only has TypeInfo.DeclaredProperties :(  Is there a better way to do this instead?

**Comment by Praburaj** [comment]
@HaoK Merging this PR per the discussion.

**Pull request merged**
