### PR TITLE
Undo breaking change to OptionsWrapper

### PR DESCRIPTION
**Pull request by HaoK**
Fixes: https://github.com/aspnet/Home/issues/2983

Filed https://github.com/aspnet/Home/issues/3002 to remove these in 3.0

### CODE REVIEW

**Review by ajcvickers — APPROVED** [review]

**Comment by Eilon** [comment]
Can we mark them as obsolete per the guidelines mentioned in https://github.com/aspnet/Home/issues/2983 ?

**Comment by HaoK** [comment]
Is that warning really necessary in this specific case given that its non virtual and throws if its ever called?

**Comment by Eilon** [comment]
I think it'd be good to follow the guidelines, because at least the docs will be correct for anyone looking at the API refs, though I agree it's surprising if anyone in practice was calling it.

**Comment by HaoK** [comment]
Okay if the docs will reflect it, that's pretty useful, I"ll send another PR

**Pull request merged**
