### PR TITLE
Depend on the DI Interfaces package instead of the implementation package

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
Relies on https://github.com/aspnet/DependencyInjection/pull/195

/cc @HaoK @davidfowl @Eilon

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@GrabYourPitchforks__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Levi Broderick). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla2.msopentech.com.
    </p>

TTYL, MSOTBOT;

**Comment by HaoK** [comment]
:shipit: once the DI change goes in

**Comment by davidfowl** [comment]
:shipit: very nice

**Comment by GrabYourPitchforks** [comment]
:heart: refactoring

**Pull request merged**
